services:
  broker:
    image: maateen/docker-beanstalkd:1.12-alpine-latest
    volumes:
      - beanstalkd112_broker_data:/var/cache/beanstalkd
    networks:
      beanstalkd112_network_local:
        aliases:
          - broker.beanstalkd112.devbox.local
    hostname: broker.beanstalkd112.devbox.local
    ports:
      - ${DEVBOX_BEANSTALKD112_BROKER_PORT:-21300}:11300
  beanstalk-console:
    image: ghcr.io/joubertredrat/devbox-containers/ptrofimov-beanstalk-console:1.7.19
    depends_on:
      broker:
        condition: service_healthy
    environment:
      BEANSTALKD_HOST: broker.beanstalkd112.devbox.local
      BEANSTALKD_PORT: 11300
    networks:
      beanstalkd112_network_local:
        aliases:
          - beanstalk-console.beanstalkd112.devbox.local
    hostname: beanstalk-console.beanstalkd112.devbox.local
    ports:
      - ${DEVBOX_BEANSTALKD112_BEANSTALK_CONSOLE_PORT:-21301}:80
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  beanstalkd112_broker_data:

networks:
  beanstalkd112_network_local:
    driver: bridge
