services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DEVBOX_MYSQL57_ROOT_PASSWORD:-password}
    volumes:
      - mysql57_data:/var/lib/mysql
    networks:
      mysql57_network_local:
        aliases:
          - db.mysql57.devbox.local
    hostname: db.mysql57.devbox.local
    ports:
      - ${DEVBOX_MYSQL57_DB_EXPORT_PORT:-13306}:3306
    healthcheck:
      test: mysqladmin -p${DEVBOX_MYSQL57_ROOT_PASSWORD:-password} ping -h localhost
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db.mysql57.devbox.local
      PMA_USER: root
      PMA_PASSWORD: ${DEVBOX_MYSQL57_ROOT_PASSWORD:-password}
    networks:
      mysql57_network_local:
        aliases:
          - phpmyadmin.mysql57.devbox.local
    hostname: phpmyadmin.mysql57.devbox.local
    ports:
      - ${DEVBOX_MYSQL57_PMA_EXPORT_PORT:-13407}:80
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1"]
      interval: 3s
      timeout: 1s
      retries: 20
  adminer:
    image: adminer:4
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: db.mysql57.devbox.local
    networks:
      mysql57_network_local:
        aliases:
          - adminer.mysql57.devbox.local
    hostname: adminer.mysql57.devbox.local
    ports:
      - ${DEVBOX_MYSQL57_ADMINER_EXPORT_PORT:-13408}:8080
    healthcheck:
      test: "php -r 'exit(strpos(file_get_contents(\"http://localhost:8080/\"), \"Adminer\") !== false ? 0 : 1);'"
      interval: 3s
      timeout: 1s
      retries: 20
  dbgate:
    image: dbgate/dbgate:alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONNECTIONS: mysql1
      LABEL_mysql1: db.mysql57.devbox.local
      SERVER_mysql1: db.mysql57.devbox.local
      USER_mysql1: root
      PASSWORD_mysql1: ${DEVBOX_MYSQL57_ROOT_PASSWORD:-password}
      PORT_mysql1: 3306
      ENGINE_mysql1: mysql@dbgate-plugin-mysql
    networks:
      mysql57_network_local:
        aliases:
          - dbgate.mysql57.devbox.local
    hostname: dbgate.mysql57.devbox.local
    ports:
      - ${DEVBOX_MYSQL57_DBGATE_EXPORT_PORT:-13409}:3000
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "3000"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  mysql57_data:

networks:
  mysql57_network_local:
    driver: bridge
