services:
  db:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEVBOX_MONGO80_DB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DEVBOX_MONGO80_DB_PASSWORD:-password}
    volumes:
      - mongo80_db_data:/data/db
    networks:
      mongo80_network_local:
        aliases:
          - db.mongo80.devbox.local
    hostname: db.mongo80.devbox.local
    ports:
      - ${DEVBOX_MONGO80_DB_EXPORT_PORT:-31017}:27017
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "127.0.0.1/test", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"]
      start_period: 10s
      interval: 3s
      timeout: 1s
      retries: 20
  mongo-express:
    image: mongo-express:1
    depends_on:
      db:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_SERVER: db.mongo80.devbox.local
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DEVBOX_MONGO80_DB_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DEVBOX_MONGO80_DB_PASSWORD:-password}
      ME_CONFIG_BASICAUTH_USERNAME: ${DEVBOX_MONGO80_MONGOEXPRESS_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DEVBOX_MONGO80_MONGOEXPRESS_PASSWORD:-password}
    networks:
      mongo80_network_local:
        aliases:
          - mongo-express.mongo80.devbox.local
    hostname: mongo-express.mongo80.devbox.local
    ports:
      - ${DEVBOX_MONGO80_EXPRESS_EXPORT_PORT:-31018}:8081
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 3s
      timeout: 1s
      retries: 40
  dbgate:
    image: dbgate/dbgate:alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONNECTIONS: mongo1
      ENGINE_mongo1: mongo@dbgate-plugin-mongo
      LABEL_mongo1: db.mongo80.devbox.local
      SERVER_mongo1: db.mongo80.devbox.local
      PORT_mongo1: 27017
      USER_mongo1: ${DEVBOX_MONGO80_DB_USER:-root}
      PASSWORD_mongo1: ${DEVBOX_MONGO80_DB_PASSWORD:-password}
    networks:
      mongo80_network_local:
        aliases:
          - dbgate.mongo80.devbox.local
    hostname: dbgate.mongo80.devbox.local
    ports:
      - ${DEVBOX_MONGO80_DBGATE_EXPORT_PORT:-31019}:3000
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "3000"]
      interval: 3s
      timeout: 1s
      retries: 20
  nosqlclient:
    image: mongoclient/mongoclient:4.0.1
    depends_on:
      db:
        condition: service_healthy
    environment:
      MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://${DEVBOX_MONGO80_DB_USER:-root}:${DEVBOX_MONGO80_DB_PASSWORD:-password}@db.mongo80.devbox.local:27017
    volumes:
      - mongo80_nosqlclient_data:/data/db
    networks:
      mongo80_network_local:
        aliases:
          - nosqlclient.mongo80.devbox.local
    hostname: nosqlclient.mongo80.devbox.local
    ports:
      - ${DEVBOX_MONGO80_NOSQLCLIENT_EXPORT_PORT:-31020}:3000
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1:3000"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  mongo80_db_data:
  mongo80_nosqlclient_data:

networks:
  mongo80_network_local:
    driver: bridge
