services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - kafka61_zookeeper_data:/data
    networks:
      kafka61_network_local:
        aliases:
          - zookeeper.kafka61.devbox.local
    hostname: zookeeper.kafka61.devbox.local
    ports:
      - ${DEVBOX_KAFKA61_ZOOKEEPER_EXPORT_PORT:-22181}:2181
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "2181"]
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20
  broker1:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.kafka61.devbox.local:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 36000
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker1.kafka61.devbox.local:19092,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
    volumes:
      - kafka61_broker1_data:/var/lib/kafka/data
    networks:
      kafka61_network_local:
        aliases:
          - broker1.kafka61.devbox.local
    hostname: broker1.kafka61.devbox.local
    ports:
      - 9092:9092
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "9092"]
      start_period: 80s
      interval: 3s
      timeout: 1s
      retries: 20
  broker2:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      zookeeper:
        condition: service_healthy
      broker1:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.kafka61.devbox.local:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker2.kafka61.devbox.local:19093,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
    volumes:
      - kafka61_broker2_data:/var/lib/kafka/data
    networks:
      kafka61_network_local:
        aliases:
          - broker2.kafka61.devbox.local
    hostname: broker2.kafka61.devbox.local
    ports:
      - 9093:9093
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "9093"]
      start_period: 80s
      interval: 3s
      timeout: 1s
      retries: 20
  broker3:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      zookeeper:
        condition: service_healthy
      broker1:
        condition: service_healthy
      broker2:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.kafka61.devbox.local:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker3.kafka61.devbox.local:19094,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
    volumes:
      - kafka61_broker3_data:/var/lib/kafka/data
    networks:
      kafka61_network_local:
        aliases:
          - broker3.kafka61.devbox.local
    hostname: broker3.kafka61.devbox.local
    ports:
      - 9094:9094
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "9094"]
      start_period: 80s
      interval: 3s
      timeout: 1s
      retries: 20
  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    depends_on:
      broker1:
        condition: service_healthy
      broker2:
        condition: service_healthy
      broker3:
        condition: service_healthy
    environment:
      KAFKA_BROKERCONNECT: broker1.kafka61.devbox.local:19092
    networks:
      kafka61_network_local:
        aliases:
          - kafdrop.kafka61.devbox.local
    hostname: kafdrop.kafka61.devbox.local
    ports:
      - ${DEVBOX_KAFKA61_KAFROP_EXPORT_PORT:-29092}:9000
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1:9000"]
      interval: 3s
      timeout: 1s
      retries: 40
  kafka-ui:
    image: provectuslabs/kafka-ui:0.0.10
    depends_on:
      broker1:
        condition: service_healthy
      broker2:
        condition: service_healthy
      broker3:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: broker1.kafka61.devbox.local:19092
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker1.kafka61.devbox.local:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper.kafka61.devbox.local:2181
    networks:
      kafka61_network_local:
        aliases:
          - kafka-ui.kafka61.devbox.local
    hostname: kafka-ui.kafka61.devbox.local
    ports:
      - ${DEVBOX_KAFKA61_KAFKAUI_EXPORT_PORT:-29093}:8080
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1:8080"]
      interval: 3s
      timeout: 1s
      retries: 20
  kowl:
    image: quay.io/cloudhut/kowl:master
    depends_on:
      broker1:
        condition: service_healthy
      broker2:
        condition: service_healthy
      broker3:
        condition: service_healthy
    environment:
      KAFKA_BROKERS: broker1.kafka61.devbox.local:19092
    networks:
      kafka61_network_local:
        aliases:
          - kowl.kafka61.devbox.local
    hostname: kowl.kafka61.devbox.local
    ports:
      - ${DEVBOX_KAFKA61_KOWL_EXPORT_PORT:-29094}:8080
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8080"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  kafka61_zookeeper_data:
  kafka61_broker1_data:
  kafka61_broker2_data:
  kafka61_broker3_data:

networks:
  kafka61_network_local:
    driver: bridge
