services:
  db:
    image: redis:7.0-alpine
    volumes:
      - redis70_db_data:/var/lib/redis
    networks:
      redis70_network_local:
        aliases:
          - db.redis70.devbox.local
    hostname: db.redis70.devbox.local
    ports:
      - ${DEVBOX_REDIS70_DB_EXPORT_PORT:-17379}:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 3s
      timeout: 1s
      retries: 20
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      REDIS_1_NAME: db.redis70.devbox.local
      REDIS_1_HOST: db.redis70.devbox.local
      REDIS_1_PORT: 6379
    networks:
      redis70_network_local:
        aliases:
          - phpredisadmin.redis70.devbox.local
    hostname: phpredisadmin.redis70.devbox.local
    ports:
      - ${DEVBOX_REDIS70_PRA_EXPORT_PORT:-17380}:80
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1"]
      interval: 3s
      timeout: 1s
      retries: 20
  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      REDIS_HOSTS: db.redis70.devbox.local:db.redis70.devbox.local:6379
    networks:
      redis70_network_local:
        aliases:
          - redis-commander.redis70.devbox.local
    hostname: redis-commander.redis70.devbox.local
    ports:
      - ${DEVBOX_REDIS70_COMMANDER_EXPORT_PORT:-17381}:8081
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  redis70_db_data:

networks:
  redis70_network_local:
    driver: bridge
