services:
  db:
    image: mongo:4.4-bionic
    volumes:
      - mongo44_db_data:/data/db
    networks:
      mongo44_network_local:
        aliases:
          - db.mongo44.devbox.local
    hostname: db.mongo44.devbox.local
    ports:
      - ${DEVBOX_MONGO44_DB_EXPORT_PORT:-27017}:27017
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "127.0.0.1/test", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"]
      start_period: 10s
      interval: 3s
      timeout: 1s
      retries: 20
  mongo-express:
    image: mongo-express:0.54
    depends_on:
      db:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_SERVER: db.mongo44.devbox.local
    networks:
      mongo44_network_local:
        aliases:
          - mongo-express.mongo44.devbox.local
    hostname: mongo-express.mongo44.devbox.local
    ports:
      - ${DEVBOX_MONGO44_EXPRESS_EXPORT_PORT:-27018}:8081
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 3s
      timeout: 1s
      retries: 40
  dbgate:
    image: dbgate/dbgate:alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONNECTIONS: mongo1
      ENGINE_mongo1: mongo@dbgate-plugin-mongo
      LABEL_mongo1: db.mongo44.devbox.local
      SERVER_mongo1: db.mongo44.devbox.local
      PORT_mongo1: 27017
    networks:
      mongo44_network_local:
        aliases:
          - dbgate.mongo44.devbox.local
    hostname: dbgate.mongo44.devbox.local
    ports:
      - ${DEVBOX_MONGO44_DBGATE_EXPORT_PORT:-27019}:3000
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "3000"]
      interval: 3s
      timeout: 1s
      retries: 20
  nosqlclient:
    image: mongoclient/mongoclient:4.0.1
    depends_on:
      db:
        condition: service_healthy
    environment:
      MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://db.mongo44.devbox.local:27017
    volumes:
      - mongo44_nosqlclient_data:/data/db
    networks:
      mongo44_network_local:
        aliases:
          - nosqlclient.mongo44.devbox.local
    hostname: nosqlclient.mongo44.devbox.local
    ports:
      - ${DEVBOX_MONGO44_NOSQLCLIENT_EXPORT_PORT:-27020}:3000
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1:3000"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  mongo44_db_data:
  mongo44_nosqlclient_data:

networks:
  mongo44_network_local:
    driver: bridge
