services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DEVBOX_POSTGRES17_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${DEVBOX_POSTGRES17_POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${DEVBOX_POSTGRES17_POSTGRES_DB:-dev}
    volumes:
      - postgres17_db_data:/var/lib/postgresql/data
    networks:
      postgres17_network_local:
        aliases:
          - db.postgres17.devbox.local
    hostname: db.postgres17.devbox.local
    ports:
      - ${DEVBOX_POSTGRES17_DB_EXPORT_PORT:-18442}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20
  pgadmin:
    image: dpage/pgadmin4:8
    depends_on:
      db:
        condition: service_healthy
    user: root
    configs:
      - source: pgadmin_servers
        target: /pgadmin4/servers.json
      - source: pgadmin_pgpass
        target: /pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@devbox.local
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: "True"
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: "['local']"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    networks:
      postgres17_network_local:
        aliases:
          - pgadmin.postgres17.devbox.local
    hostname: pgadmin.postgres17.devbox.local
    ports:
      - ${DEVBOX_POSTGRES17_PGADMIN_EXPORT_PORT:-18443}:80
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "80"]
      start_period: 100s
      interval: 3s
      timeout: 1s
      retries: 60
  pgweb:
    image: sosedoff/pgweb:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${DEVBOX_POSTGRES17_POSTGRES_USER:-postgres}:${DEVBOX_POSTGRES17_POSTGRES_PASSWORD:-password}@db.postgres17.devbox.local:5432/${DEVBOX_POSTGRES17_POSTGRES_DB:-dev}?sslmode=disable
    networks:
      postgres17_network_local:
        aliases:
          - pgweb.postgres17.devbox.local
    hostname: pgweb.postgres17.devbox.local
    ports:
      - ${DEVBOX_POSTGRES17_PGWEB_EXPORT_PORT:-18444}:8081
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 3s
      timeout: 1s
      retries: 20
  dbgate:
    image: dbgate/dbgate:alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONNECTIONS: postgres1
      ENGINE_postgres1: postgres@dbgate-plugin-postgres
      LABEL_postgres1: db.postgres17.devbox.local
      SERVER_postgres1: db.postgres17.devbox.local
      PORT_postgres1: 5432
      USER_postgres1: ${DEVBOX_POSTGRES17_POSTGRES_USER:-postgres}
      PASSWORD_postgres1: ${DEVBOX_POSTGRES17_POSTGRES_PASSWORD:-password}
    networks:
      postgres17_network_local:
        aliases:
          - dbgate.postgres17.devbox.local
    hostname: dbgate.postgres17.devbox.local
    ports:
      - ${DEVBOX_POSTGRES17_DBGATE_EXPORT_PORT:-18445}:3000
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "3000"]
      interval: 3s
      timeout: 1s
      retries: 20

configs:
  pgadmin_pgpass:
    content: db.postgres17.devbox.local:5432:*:${DEVBOX_POSTGRES17_POSTGRES_USER:-postgres}:${DEVBOX_POSTGRES17_PGADMIN_PASSWORD:-password}
  pgadmin_servers:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "db.postgres17.devbox.local",
        "Host": "db.postgres17.devbox.local",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "${DEVBOX_POSTGRES17_POSTGRES_USER:-postgres}",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}

volumes:
  postgres17_db_data:

networks:
  postgres17_network_local:
    driver: bridge
