services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${DEVBOX_MARIADB106_ROOT_PASSWORD:-password}
    volumes:
      - mariadb106_data:/var/lib/mysql
    networks:
      mariadb106_network_local:
        aliases:
          - db.mariadb106.devbox.local
    hostname: db.mariadb106.devbox.local
    ports:
      - ${DEVBOX_MARIADB106_DB_EXPORT_PORT:-14306}:3306
    healthcheck:
      test: mysqladmin -p${DEVBOX_MARIADB106_ROOT_PASSWORD:-password} ping -h localhost
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db.mariadb106.devbox.local
      PMA_USER: root
      PMA_PASSWORD: ${DEVBOX_MARIADB106_ROOT_PASSWORD:-password}
    networks:
      mariadb106_network_local:
        aliases:
          - phpmyadmin.mariadb106.devbox.local
    hostname: phpmyadmin.mariadb106.devbox.local
    ports:
      - ${DEVBOX_MARIADB106_PMA_EXPORT_PORT:-14307}:80
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1"]
      interval: 3s
      timeout: 1s
      retries: 20
  adminer:
    image: adminer:4
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: db.mariadb106.devbox.local
    networks:
      mariadb106_network_local:
        aliases:
          - adminer.mariadb106.devbox.local
    hostname: adminer.mariadb106.devbox.local
    ports:
      - ${DEVBOX_MARIADB106_ADMINER_EXPORT_PORT:-14308}:8080
    healthcheck:
      test: "php -r 'exit(strpos(file_get_contents(\"http://localhost:8080/\"), \"Adminer\") !== false ? 0 : 1);'"
      interval: 3s
      timeout: 1s
      retries: 20
  dbgate:
    image: dbgate/dbgate:alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONNECTIONS: mariadb1
      LABEL_mariadb1: db.mariadb106.devbox.local
      SERVER_mariadb1: db.mariadb106.devbox.local
      USER_mariadb1: root
      PASSWORD_mariadb1: ${DEVBOX_MARIADB106_ROOT_PASSWORD:-password}
      PORT_mariadb1: 3306
      ENGINE_mariadb1: mysql@dbgate-plugin-mysql
    networks:
      mariadb106_network_local:
        aliases:
          - dbgate.mariadb106.devbox.local
    hostname: dbgate.mariadb106.devbox.local
    ports:
      - ${DEVBOX_MARIADB106_DBGATE_EXPORT_PORT:-14309}:3000
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "3000"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  mariadb106_data:

networks:
  mariadb106_network_local:
    driver: bridge
